POST http://localhost:9000/register HTTP/1.1
Content-Type: application/json

{
  "username": "user10",
  "email": "user10@gmail.com",
  "password": "user10",
  "name": "Test User10"
}

###
POST http://localhost:9000/login HTTP/1.1
Content-Type: application/json

{
  "email": "user10@gmail.com",
  "password": "user10"
}




###
GET http://localhost:9000/get_user_and_profile HTTP/1.1
Authorization: Bearer fbced5c4d86b0c3def7bde6a5854be8abf25580096614d1e8021bd120df0865d
Content-Type: application/json

###
POST http://localhost:9000/update_profile_data HTTP/1.1
Authorization: Bearer 695cab070a4fcff00d8d56092b34fc855b44209dfaac03b64eae0ba2d8479aa3
Content-Type: application/json

{
  "bio": "Full-stack MERN developer passionate about building scalable web applications.",
  "currentPost": "Software Engineer Intern",

  "pastWork": [
    {
      "company": "TechNova Solutions",
      "position": "Frontend Developer",
      "years": "2023 - 2024"
    },
    {
      "company": "CodeCraft Labs",
      "position": "Backend Developer",
      "years": "2022 - 2023"
    }
  ],

  "education": [
    {
      "school": "Government College of Engineering and Leather Technology",
      "degree": "Bachelors",
      "fieldOfStudy": "Information Technology"
    },
    {
      "school": "XYZ Polytechnic",
      "degree": "Diploma",
      "fieldOfStudy": "Electrical Engineering"
    }
  ]
}

###
GET http://localhost:9000/get_all_users HTTP/1.1
Authorization: Bearer fbced5c4d86b0c3def7bde6a5854be8abf25580096614d1e8021bd120df0865d
Content-Type: application/json

###
GET http://localhost:9000/user/download_resume
Authorization: Bearer fbced5c4d86b0c3def7bde6a5854be8abf25580096614d1e8021bd120df0865d

###
POST http://localhost:9000/post HTTP/1.1
Authorization: Bearer fbced5c4d86b0c3def7bde6a5854be8abf25580096614d1e8021bd120df0865d
Content-Type: application/json

{
  "body": "This is my first post!"
}