POST http://localhost:9000/register HTTP/1.1
Content-Type: application/json

{
  "username": "user10",
  "email": "user10@gmail.com",
  "password": "user10",
  "name": "Test User10"
}

###
POST http://localhost:9000/login HTTP/1.1
Content-Type: application/json

{
  "email": "user10@gmail.com",
  "password": "user10"
}




###
GET http://localhost:9000/get_user_and_profile HTTP/1.1
Authorization: Bearer bcddd6b232678390cfb901332d8338f97ecaef45f839d099c4329ede15642e81
Content-Type: application/json

###
POST http://localhost:9000/update_profile_data HTTP/1.1
Authorization: Bearer bcddd6b232678390cfb901332d8338f97ecaef45f839d099c4329ede15642e81
Content-Type: application/json

{
  "bio": "Full-stack MERN developer passionate about building scalable web applications.",
  "currentPost": "Software Engineer Intern",

  "pastWork": [
    {
      "company": "TechNova Solutions",
      "position": "Frontend Developer",
      "years": "2023 - 2024"
    },
    {
      "company": "CodeCraft Labs",
      "position": "Backend Developer",
      "years": "2022 - 2023"
    }
  ],

  "education": [
    {
      "school": "Government College of Engineering and Leather Technology",
      "degree": "Bachelors",
      "fieldOfStudy": "Information Technology"
    },
    {
      "school": "XYZ Polytechnic",
      "degree": "Diploma",
      "fieldOfStudy": "Electrical Engineering"
    }
  ]
}

###
GET http://localhost:9000/get_all_users HTTP/1.1
Authorization: Bearer bcddd6b232678390cfb901332d8338f97ecaef45f839d099c4329ede15642e81
Content-Type: application/json

###
GET http://localhost:9000/user/download_resume
Authorization: Bearer bcddd6b232678390cfb901332d8338f97ecaef45f839d099c4329ede15642e81

###
POST http://localhost:9000/post HTTP/1.1
Authorization: Bearer bcddd6b232678390cfb901332d8338f97ecaef45f839d099c4329ede15642e81
Content-Type: application/json

{
  "body": "This is my first post!"
}